const envCfg = require('env.cfg')
const API_URL = envCfg.api + envCfg.apiPrefix

export default {
  userLogin: API_URL + '/account/login',
  userRegister: API_URL + '/account/register',
  checkMobileExist: API_URL + '/account/mobileExist',
  getCode: API_URL + '/sms/send',
  checkCaptcha: API_URL + '/account/checkCaptcha/',
  resetPassword: API_URL + '/account/resetPassword',
  changePassword: API_URL + '/account/changePassword',
  getCurrentUserInfo: API_URL + '/user/getCurrentUserInfo',
  saveCurrentUserInfo: API_URL + '/user/saveCurrentUserInfo',
  getUserInfo: API_URL + '/user/getUserInfo',
  userLogOut: API_URL + '/account/logout',
  uploadImg: API_URL + '/oss/uploadImg',
  getTicket: API_URL + '/account/getTicket',
  uploadImageTmp: API_URL + '/oss/uploadFile',
  uploadFiles: API_URL + '/oss/uploadFiles',
  getProvince: API_URL + '/area/getProvince',
  setInvoiceTitle: API_URL + '/invoice/setInvoiceTitle',
  getInvoiceTitle: API_URL + '/invoice/getInvoiceTitle',
  getQuestion: API_URL + '/questionnaire/getDesignerQuestionnaire',
  saveQuestion: API_URL + '/questionnaire/saveQuestionnaireAnswer',
  listOrderInfo: API_URL + '/order/queryPageTradeOrder',
  setDesignerRemark: API_URL + '/designer/updateRemark',
  getOrderDetail: API_URL + '/order/queryOrderDetail',
  receiveOrder: API_URL + '/order/receive',
  activateOrder: API_URL + '/order/activate',
  frozenOrder: API_URL + '/order/frozen',
  cancelOrder: API_URL + '/order/cancel',
  submitOrder: API_URL + '/order/submitOrder',
  getCompanyInfo: API_URL + '/sellerCompany/getSellerCompanyInfo',
  getCompanyService: API_URL + '/sellerCompany/getSellerCompanyService',
  getCompanyIM: API_URL + '/sellerCompany/getCompanyIM/',
  getCardList: API_URL + '/pay/queryBindBankCardDesigner',
  confirmOrderPrice: API_URL + '/order/activate',
  bindCardForFastPay: API_URL + '/pay/requireBindBankCardDesigner',
  verifySmsCode: API_URL + '/pay/verifySmsCode',
  createPayOrder: API_URL + '/pay/createPayOrder'
}
